[package]
distribution = "2201.8.4"
org = "azeem"
name = "apns"
version = "@toml.version@"
repository = "https://github.com/AzeemMuzammil/ballerina-apns"
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
